sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t saulet/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true saulet/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker-react-v2"
    env: "Dockerreactv2-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-212567022682"
    # bucket_path: "docker-react-v2"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
