sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t saulet/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true saulet/docker-react npm run test

